# Site settings
title: Dave Vasilevsky
email: dave@vasilevsky.ca
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vasilevsky.ca" # the base hostname & protocol for your site
twitter_username: djvasi
github_username:  vasi

# Build settings
markdown: kramdown
